[package]
name = "structdiff"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/knickish/structdiff"
description = """zero-dependency crate for generating and applying partial diffs between struct instances"""


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structdiff-derive = {path = "derive", version = "=0.1.0"}