[package]
name = "structdiff-derive"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>", "Fedor <not.fl3@gmail.com>", "Kirk <knickish@gmail.com"]
edition = "2018"
description = "Fork of nanoserde's parsing library"
license = "MIT"

[lib]
proc-macro = true

